export { DE } from './dice-expression-domain'
export {
  type DiceBinOp,
  type DiceUnOp,
  type DiceReducer,
  type SimpleReducer,
  type CountReducer,
  type LowHigh,
  always,
  between,
  binaryOp,
  composite,
  compound,
  customDie,
  die,
  diceListWithFilter,
  diceListWithMap,
  diceReduce,
  diceExpressions,
  drop,
  emphasis,
  explode,
  filterableDiceArray,
  filterableDiceExpressions,
  infiniteReroll,
  keep,
  literal,
  dropOrKeepShouldBePositive,
  emptyFaces,
  emptySet,
  insufficientSides,
  tooManyDrops,
  tooManyKeeps,
  exact,
  upTo,
  valueOrLess,
  valueOrMore,
  diceVariableRef,
  nDice,
  nDiceLit,
  nDiceVar,
  diceListWithMapHomogeneous,
  homogeneousDiceExpressions,
  homogeneousCustomDice,
  filterableHomogeneous,
  filterableHomogeneousCustom,
} from './dice-expression'

export type {
  Always,
  Between,
  BinaryOp,
  Composite,
  Compound,
  CustomDie,
  DiceExpression,
  DiceExpressions,
  DiceFunctor,
  DiceReduce,
  Die,
  DiceFilter,
  DiceFilterable,
  DiceListWithFilter,
  DiceListWithMap,
  DiceReduceable,
  Drop,
  DropOrKeepShouldBePositive,
  EmptyFaces,
  EmptySet,
  Exact,
  Emphasis,
  Explode,
  FilterableDiceArray,
  FilterableDiceExpressions,
  InfiniteReroll,
  InsufficientSides,
  Keep,
  Literal,
  Range,
  Reroll,
  Roll,
  Sides,
  Times,
  TooManyDrops,
  TooManyKeeps,
  UnaryOp,
  ValidationMessage,
  UpTo,
  ValueOrLess,
  ValueOrMore,
  DiceVariableRef,
  NDice,
  NDiceParam,
  DiceListWithMapHomogeneous,
  HomogeneousDiceExpressions,
  HomogeneousCustomDice,
  FilterableHomogeneous,
  FilterableHomogeneousCustom,
} from './dice-expression'

export { DiceParser } from './dice-parser'
export type { ParseError, ParseWithErrorsResult } from './parse-error'
export { suggestKeyword } from './parse-error'

export { RR } from './roll-result-domain'

export {
  type BinaryOpResult,
  type CustomDieResult,
  type DiceExpressionsResult,
  type DiceFilterableResult,
  type DiceMapeableResult,
  type DiceReduceResult,
  type DieResult,
  type DiceReduceableResult,
  type DiceResultMapped,
  type DieResultFilter,
  type DiscardResult,
  type Compounded,
  type Exploded,
  type KeepResult,
  type LiteralResult,
  type Normal,
  type OneResult,
  type Rerolled,
  type RollResult,
  type UnaryOpResult,
  binaryOpResult,
  compounded,
  customDieResult,
  diceExpressionsResult,
  diceFilterableResult,
  diceMapeableResult,
  diceReduceResult,
  dieResult,
  discardResult,
  exploded,
  keepResult,
  literalResult,
  normal,
  oneResult,
  rerolled,
  unaryOpResult,
} from './roll-result'

export { Roller, type RollerOptions, MAX_DICE_COUNT } from './roller'

export { DiceStats } from './dice-stats'

export type {
  Program,
  Statement,
  Assignment,
  ExpressionStatement,
  Expression,
  NumberLiteral,
  BooleanLiteral,
  StringLiteral,
  VariableRef,
  DiceExpr,
  BinaryExpr,
  BinaryOper,
  UnaryExpr,
  IfExpr,
  RecordExpr,
  RecordField,
  ArrayExpr,
  RepeatExpr,
  FieldAccess,
  IndexAccess,
  MatchExpr,
  MatchArm,
  MatchPattern,
  Value,
  RuntimeError,
  ParameterDeclaration,
  ParameterSpec,
  ParameterDefault,
} from './program'

export {
  program,
  assignment,
  expressionStatement,
  numberLiteral,
  booleanLiteral,
  stringLiteral,
  variableRef,
  diceExpr,
  binaryExpr,
  unaryExpr,
  ifExpr,
  recordExpr,
  arrayExpr,
  repeatExpr,
  fieldAccess,
  indexAccess,
  matchExpr,
  matchArm,
  wildcardPattern,
  expressionPattern,
  runtimeError,
  parameterDeclaration,
} from './program'

export { Evaluator, type RunOptions } from './evaluator'
export { ProgramParameters, type Parameter } from './program-parameters'
export {
  ProgramStats,
  suggestBucketSize,
  binDistribution,
  type FieldStats,
  type DiscriminatedVariant,
  type Percentiles,
  type NumberAggregateStats,
  type Tier,
  type AnalysisStrategy,
  type AnalyzeResult,
  type AnalyzeOptions,
  type AnalyzeAsyncOptions,
  type AsyncProgress,
  type AnalyzeDiagnostics,
} from './program-stats'
export { ProgramParser, type ParseProgramResult } from './program-parser'
export {
  fieldStatsToJSON,
  fieldStatsFromJSON,
  totalVariationDistance,
  klDivergence,
  probabilityGreaterThan,
  sampleFromDistribution,
  fieldFromRecord,
  elementFromArray,
} from './program-stats-utils'

export { Distribution } from './distribution'
