export { DE } from './dice-expression-domain'
export {
  type DiceBinOp,
  type DiceUnOp,
  type DiceReducer,
  type SimpleReducer,
  type CountReducer,
  type LowHigh,
  always,
  between,
  binaryOp,
  composite,
  compound,
  customDie,
  die,
  diceListWithFilter,
  diceListWithMap,
  diceReduce,
  diceExpressions,
  drop,
  emphasis,
  explode,
  filterableDiceArray,
  filterableDiceExpressions,
  infiniteReroll,
  keep,
  literal,
  dropOrKeepShouldBePositive,
  emptyFaces,
  emptySet,
  insufficientSides,
  tooManyDrops,
  tooManyKeeps,
  exact,
  upTo,
  valueOrLess,
  valueOrMore,
  diceVariableRef,
} from './dice-expression'

export type {
  Always,
  Between,
  BinaryOp,
  Composite,
  Compound,
  CustomDie,
  DiceExpression,
  DiceExpressions,
  DiceFunctor,
  DiceReduce,
  Die,
  DiceFilter,
  DiceFilterable,
  DiceListWithFilter,
  DiceListWithMap,
  DiceReduceable,
  Drop,
  DropOrKeepShouldBePositive,
  EmptyFaces,
  EmptySet,
  Exact,
  Emphasis,
  Explode,
  FilterableDiceArray,
  FilterableDiceExpressions,
  InfiniteReroll,
  InsufficientSides,
  Keep,
  Literal,
  Range,
  Reroll,
  Roll,
  Sides,
  Times,
  TooManyDrops,
  TooManyKeeps,
  UnaryOp,
  ValidationMessage,
  UpTo,
  ValueOrLess,
  ValueOrMore,
  DiceVariableRef,
} from './dice-expression'

export { DiceParser } from './dice-parser'
export type { ParseError, ParseWithErrorsResult } from './parse-error'
export { suggestKeyword } from './parse-error'

export { RR } from './roll-result-domain'

export {
  type BinaryOpResult,
  type CustomDieResult,
  type DiceExpressionsResult,
  type DiceFilterableResult,
  type DiceMapeableResult,
  type DiceReduceResult,
  type DieResult,
  type DiceReduceableResult,
  type DiceResultMapped,
  type DieResultFilter,
  type DiscardResult,
  type Compounded,
  type Exploded,
  type KeepResult,
  type LiteralResult,
  type Normal,
  type OneResult,
  type Rerolled,
  type RollResult,
  type UnaryOpResult,
  binaryOpResult,
  compounded,
  customDieResult,
  diceExpressionsResult,
  diceFilterableResult,
  diceMapeableResult,
  diceReduceResult,
  dieResult,
  discardResult,
  exploded,
  keepResult,
  literalResult,
  normal,
  oneResult,
  rerolled,
  unaryOpResult,
} from './roll-result'

export { Roller, type RollerOptions } from './roller'

export { DiceStats } from './dice-stats'

export type {
  Program,
  Statement,
  Assignment,
  ExpressionStatement,
  Expression,
  NumberLiteral,
  BooleanLiteral,
  StringLiteral,
  VariableRef,
  DiceExpr,
  BinaryExpr,
  BinaryOper,
  UnaryExpr,
  IfExpr,
  RecordExpr,
  RecordField,
  ArrayExpr,
  RepeatExpr,
  FieldAccess,
  IndexAccess,
  Value,
  RuntimeError,
} from './program'

export {
  program,
  assignment,
  expressionStatement,
  numberLiteral,
  booleanLiteral,
  stringLiteral,
  variableRef,
  diceExpr,
  binaryExpr,
  unaryExpr,
  ifExpr,
  recordExpr,
  arrayExpr,
  repeatExpr,
  fieldAccess,
  indexAccess,
  runtimeError,
} from './program'

export { Evaluator } from './evaluator'
export {
  ProgramStats,
  suggestBucketSize,
  binDistribution,
  type FieldStats,
  type Percentiles,
  type NumberAggregateStats,
  type Tier,
  type AnalysisStrategy,
  type AnalyzeResult,
} from './program-stats'
export { ProgramParser, type ParseProgramResult } from './program-parser'
export {
  fieldStatsToJSON,
  fieldStatsFromJSON,
  totalVariationDistance,
  klDivergence,
  probabilityGreaterThan,
  sampleFromDistribution,
  fieldFromRecord,
  elementFromArray,
} from './program-stats-utils'
